Refatora todos os models trocando CharField para TextField
scieloorg/core pull request #117
Opened 2023-02-28 07:48 UTC by rg3915

#### O que esse PR faz?

Refatora todos os models trocando CharField para TextField.

#### Onde a revisão poderia começar?

Lendo os commits.

#### Como este poderia ser testado manualmente?

```
make django_makemigrations
make django_migrate
```

#### Algum cenário de contexto que queira dar?

NA

#### Screenshots

NA

#### Quais são tickets relevantes?

#96

### Referências

NA

2023-02-28 12:19 UTC, robertatakenaka commented on collection/models.py
> +        FieldPanel('type_field'),
@rg3915 trocar para `collection_type`

2023-02-28 12:26 UTC, robertatakenaka commented on location/models.py
> +    name = models.CharField(_("State name"), max_length=19, unique=True)
@rg3915 não é garantia de que "nome do estado" é único no mundo.

2023-02-28 12:27 UTC, robertatakenaka commented on location/models.py
> +    region = models.CharField(_("Region"), choices=choices.regions, max_length=12, null=True, blank=True)
@rg3915 não estava neste issue, mas acho que para tornar o modelo mais flexível, migrar `region` para `Location`

2023-02-28 12:33 UTC, robertatakenaka requested changes
Verificar os comentários

2023-03-01 13:28 UTC, rg3915 commented on location/models.py
> +    region = models.CharField(_("Region"), choices=choices.regions, max_length=12, null=True, blank=True)
Vou fazer na Issue #125

2023-03-01 19:29 UTC, robertatakenaka approved these changes

2023-03-01 19:30 UTC, merged