WIP: Modelagem de Article
scieloorg/core pull request #162
Opened 2023-03-24 17:45 UTC by rg3915

#### O que esse PR faz?

Cria model `Article` e outros na app `article`.

#### Onde a revisão poderia começar?

Lendo os commits.

#### Como este poderia ser testado manualmente?

```
make up
make django_migrate
docker container logs scielo_core_local_django
```

#### Algum cenário de contexto que queira dar?

NA

#### Screenshots

NA

#### Quais são tickets relevantes?

#145

#### Referências

NA

2023-03-27 11:22 UTC, gitnnolabs requested changes

2023-03-27 11:22 UTC, gitnnolabs commented on article/models.py
> +    titles = models.ManyToManyField("Title", blank=True)
@rg3915 

Estou vendo pelo menos duas referencia para "Title", mas onde está importado esse modelo? 

@rg3915 foi gerado localmente migrações para esses modelos?

2023-03-27 11:22 UTC, gitnnolabs commented on article/models.py
> +        "AbstractModel",
Item ao comentário anterior.

2023-03-27 11:22 UTC, gitnnolabs commented on article/models.py
> +class Category(models.Model):
@rg3915 esse modelo tem como objetivo acomodar qual dado? 

Pelo que temos aqui no mínimo está confuso uma classe chamada **category** com um atributo **subject**

2023-03-31 10:29 UTC, gitnnolabs commented
@rg3915 pelo que vi não está sendo utilizado o componente de autocomplete que mencionei em reunião anteriores, correto?

2023-04-03 16:31 UTC, robertatakenaka commented on article/models.py
> +    abstract_field = models.ForeignKey(
@rg3915 
manytomany

2023-04-03 16:32 UTC, robertatakenaka commented on article/models.py
> +    issue = models.PositiveIntegerField(null=True, blank=True)
@rg3915 tudo literal, usar CharField. Já comentei anteriormente que tudo deve ser considerado literal / str.

2023-04-03 16:48 UTC, robertatakenaka reviewed
@rg3915 Para avançar / concluir este issue, leve em conta:
1. A modelagem está suficiente para apresentar os dados conforme o search.scielo.org apresenta?
2. Foco nos metadados que estão representados no XML dentro de article-meta. Não encontrei a modelagem para data de publicação que é essencial
3. Excelente desempenho na recuperação dos dados. Então, será que tudo deve virar modelo? Por exemplo, sobre os article_id, será que não é melhor simplesmente haver nomes de atributos diferentes para cada tipo de article_id?

2023-04-03 19:15 UTC, robertatakenaka commented on article/models.py
> +
DocumentTitle já está fazendo o papel de Title

2023-04-03 19:16 UTC, robertatakenaka commented on article/models.py
> +
OK porque os usuários poderão criar novos tipos

2023-05-03 12:48 UTC, closed without merging