Create collection
scieloorg/core pull request #22
Opened 2022-11-22 18:54 UTC by Rossi-Luciano

#### O que esse PR faz?
Adiciona modelo para coleções.

#### Onde a revisão poderia começar?
Por _commit_.

#### Como este poderia ser testado manualmente?
NA.

#### Algum cenário de contexto que queira dar?
NA.

### Screenshots
NA.

#### Quais são tickets relevantes?
TK #17 

### Referências
NA.

2022-11-23 13:57 UTC, robertatakenaka commented on collection/choices.py
> +    ('independent', 'Independent'),
Use `_('Certified')` no lugar de `'Certified'` para que os termos fiquem prontos para tradução

2022-11-23 14:02 UTC, robertatakenaka commented on collection/models.py
> +        return self.main_name or None
estes atributos tem que retornar `str`

2022-11-25 14:08 UTC, robertatakenaka commented on collection/models.py
> +        return u'%s' % self.main_name or None
@Rossi-Luciano só podem retornar string

2022-11-25 14:09 UTC, robertatakenaka commented on config/settings/base.py
>  	  "journal",
@Rossi-Luciano corrigir identação

2022-11-25 14:23 UTC, robertatakenaka requested changes
@Rossi-Luciano verificar comentários

2022-11-25 14:35 UTC, Rossi-Luciano commented on collection/wagtail_hooks.py
> +    list_display = ('main_name', 'type', 'institution', 'creator', 'updated', 'created', 'updated_by')
Removido.

2022-11-25 14:35 UTC, Rossi-Luciano commented on collection/models.py
> +        return u'%s' % self.main_name or None
@robertatakenaka veja se está correto.

2022-11-25 14:36 UTC, Rossi-Luciano commented on config/settings/base.py
>  	  "journal",
Corrigido.

2022-11-28 15:20 UTC, merged