Configura Haystack e Indexes para o modelo Article
scieloorg/core pull request #246
Opened 2023-06-13 14:01 UTC by samuelveigarangel

#### O que esse PR faz?
Configura a biblioteca haystack e configura os indexes para o modelo Article.

#### Onde a revisão poderia começar?
Pelo commit https://github.com/scieloorg/core/commit/56eaafd1c17919184dd205334cb60242fca4393c

#### Como este poderia ser testado manualmente?

1. make build
2. Acessa: http://0.0.0.0:8983/solr/#/core/query
3. Clica em `Execute query`

#### Algum cenário de contexto que queira dar?
1. Verifique se o processo que está executando o código possui as permissões necessárias para criar, ler e escrever nos arquivos do projeto. Isto é necessário para o processo criar a pasta data e seus respectivos arquivos.
2. Após configurar corretamente o Haystack e o Solr, você precisa criar uma classe que irá indexar os campos desejados. Uma vez feito isso, execute o seguinte comando no bash (make django_bash): python manage.py build_solr_schema > schema.xml. Esse comando irá fazer com que o Haystack crie o arquivo de schema do Solr, chamado "schema.xml".

### Screenshots
Tela no solr que mostra todos os objetos Article através da `query *:*`
![Captura de tela de 2023-06-13 10-26-58](https://github.com/scieloorg/core/assets/82840278/c9141922-23bc-452a-8a92-a0b74c647577)

Através do campo "text" configurado no ArticleIndex, é possível realizar pesquisas utilizando os seguintes campos: pid_v2, pid_v3, ano, tipo do artigo, título, autores/pesquisadores, periódico, palavras-chave e categoria. Essa configuração permite que você faça buscas abrangentes nos campos mencionados, facilitando a localização dos artigos.
![Captura de tela de 2023-06-13 10-29-49](https://github.com/scieloorg/core/assets/82840278/f010c092-76ae-42fd-b2dc-56b570095589)

É possível localizar os artigos através de um campo específico, como "researchers". Na imagem abaixo, é mostrada uma consulta que busca pelo campo "researchers".

![Captura de tela de 2023-06-13 10-30-22](https://github.com/scieloorg/core/assets/82840278/f7cffd01-2089-44dd-bb53-4fb7a16bd26d)

#### Quais são tickets relevantes?
[#90](https://github.com/scieloorg/core/issues/90)
[#242](https://github.com/scieloorg/core/issues/242)

### Referências
[Docs django-haystack](https://django-haystack.readthedocs.io/en/master/toc.html)

2023-06-20 14:53 UTC, gitnnolabs requested changes

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/schema.xml
> -    <fieldType name="int" class="solr.TrieIntField" precisionStep="0" positionIncrementGap="0"/>
Esse tipos de campos no **solr** deve permanecer, existe algum motivo para essa remoção. 

Principalmente o campo **text** que está com ``tokenizer`` importantes!

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/schema.xml
> -        <filter class="solr.LowerCaseFilterFactory" />
Idem ao comentário anterior

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/schema.xml
> -   <!-- default search -->
Também não deve ser removido!

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/schema.xml
> -   <field name="django_ct" type="string" indexed="true" stored="true" multiValued="false"/>
Também não deve ser removido esses campos são campo que fazer a "cola" entre o Solr e o Django.

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/schema.xml
> -   <field name="record_type" type="string" indexed="true" stored="true" multiValued="false"/>
Sinceramente acho que deve ser desfeita todas as modificações nesse arquivo e deve ser mantido o arquivo que temos no exemplo do PR para o OCABR.

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/solrconfig.xml
> +       <!-- <str name="echoParams">explicit</str>
Deve ser mantido o arquivo que colocamos como exemplo do PR para o OCABR. 

Qual a justificativa para essa alterações?

2023-06-20 14:53 UTC, gitnnolabs commented on index/core/conf/solrconfig.xml
>           <str name="facet">true</str>
Foi desligado os clusters por que?

2023-06-20 14:53 UTC, gitnnolabs commented on local.yml
> -
Por gentileza manter o padrão de 4 espaços nos arquivo de que utilizam tabulação!

2023-06-20 14:53 UTC, gitnnolabs commented on production.yml
> -         - ./index/ocabr:/opt/solr/server/solr/ocabr
👍

2023-06-20 15:04 UTC, samuelveigarangel commented on index/core/conf/solrconfig.xml
> +       <!-- <str name="echoParams">explicit</str>
Nessa etapa, ainda não tinha definido os facets. Ao implementar a interface de buscar, eu inseri os facets.

2023-06-20 15:06 UTC, samuelveigarangel commented on index/core/conf/solrconfig.xml
>           <str name="facet">true</str>
Nessa etapa, ainda não tinha definido os facets. Ao implementar a interface de buscar, eu inseri os facets.

2023-06-20 15:06 UTC, samuelveigarangel commented on index/core/conf/solrconfig.xml
> +       <!-- <str name="echoParams">explicit</str>
Ja foi corrigido

2023-07-28 17:13 UTC, samuelveigarangel commented
Resolvido em https://github.com/scieloorg/core/pull/255

2023-07-28 17:14 UTC, closed without merging