Cria task e suas dependencias para coletar dados journal do article meta
scieloorg/core pull request #262
Opened 2023-07-12 19:10 UTC by samuelveigarangel

#### O que esse PR faz?
Cria task e suas dependencias para coletar dados journal do article meta

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?

1. make build
2. make up
3. make django_bash
4. python manage.py runscript load_journal_from_article_meta

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
Scielo Journals
![Screenshot from 2023-07-12 16-08-09](https://github.com/scieloorg/core/assets/82840278/047fe5df-1d38-4a52-8445-9e9e995f9134)

Official Journals
![Screenshot from 2023-07-12 16-08-15](https://github.com/scieloorg/core/assets/82840278/da986d5a-a6ce-41e9-b87d-bc1593f645e4)

#### Quais são tickets relevantes?
https://github.com/scieloorg/core/issues/256

### Referências
https://github.com/scieloorg/articles_meta/blob/master/docs/source/api/journal_identifiers.rst
https://articlemeta.scielo.org/api/v1/journal/identifiers/

2023-07-13 13:34 UTC, robertatakenaka commented on core/utils/utils.py
> +)
Legal!

2023-07-13 13:35 UTC, samuelveigarangel commented on collection/controller.py
> +from article.utils.article_utils import get_or_create_language
Verdade.

2023-07-13 13:37 UTC, robertatakenaka commented on journal/utils/correspondencia.py
> +    "v35": "issn_scielo",
@samuelveigarangel na base de dados title, a tag é v400; na issue é v35.

2023-07-13 14:02 UTC, robertatakenaka commented on journal/models.py
> +        cls,
https://github.com/scieloorg/scms-upload/blob/37daecfdd8dc28bce20ff4daa990a4e6bf1ff7d2/journal/models.py#L79

2023-07-13 14:05 UTC, robertatakenaka requested changes
Todos os comentários são melhorias que devem ser feita agora ou futuramente.
Exceto `na base de dados title, a tag para issn_scielo é v400; na issue é v35.` que isso é erro mesmo.

2023-07-14 14:27 UTC, robertatakenaka approved these changes

2023-07-14 14:27 UTC, merged