Adicionar campos faltantes no OfficialJournal
scieloorg/core pull request #332
Opened 2023-08-24 14:05 UTC by samuelveigarangel

#### O que esse PR faz?
Adiciona alguns campos faltantes no modelo OfficialJournal conforme a documentação [SciELO](https://scielo.readthedocs.io/projects/scielo-pc-programs/en/latest/titlemanager_title.html).

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?

1. make up
2. make django_makemigrations
3. make django_migrate

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://github.com/scieloorg/core/assets/82840278/5ad4e0bf-fa70-4bad-8cb1-c755c5f96ca2)
![image](https://github.com/scieloorg/core/assets/82840278/add698e7-4baf-491c-b04e-732d85cba3e1)

#### Quais são tickets relevantes?
https://github.com/scieloorg/core/issues/330

### Referências
N/A

2023-08-24 14:19 UTC, robertatakenaka commented on journal/models.py
> +        _("Terminate month"), max_length=2, null=True, blank=True
@samuelveigarangel verificar se há choices para mes em alguma app e usar

2023-08-24 14:21 UTC, robertatakenaka requested changes
Verificar o comentário

2023-09-05 17:52 UTC, samuelveigarangel commented
Melhorias relacionadas aos comentários feitos nesta pull request a partir de https://github.com/scieloorg/core/pull/332/commits/02f041cfebf330737f83c447e2fbb5f60092a28c.

2023-09-06 13:07 UTC, robertatakenaka commented on journal/choices.py
> +    (_("Psicanalise"), _("Psicanalise")),
o mesmo para os demais

2023-09-06 13:09 UTC, robertatakenaka commented on journal/models.py
> +from researcher.choices import MONTHS
Talvez MONTHS esteja declarado em mais de um lugar, manter em um local em comum a todas as apps.

2023-09-06 13:15 UTC, robertatakenaka commented on journal/utils/journal_utils.py
> +def get_or_update_wos_areas(journal, wos_areas, user):
@samuelveigarangel coloque comentários indicando como é a entrada. Faça isso para todas as funções

2023-09-06 13:17 UTC, robertatakenaka commented on journal/utils/journal_utils.py
> +    data = []
@samuelveigarangel coloque comentários indicando como é o formato da entrada, colocar exemplos

2023-09-06 13:18 UTC, robertatakenaka commented on journal/utils/journal_utils.py
> +            for word in re.split(",|;", s):
os comentários devem explicar esta decisão / necessidade

2023-09-06 13:19 UTC, robertatakenaka commented on journal/utils/journal_utils.py
> +    """
Excelente! Bom colocar comentário para que o código fique mais fácil de ler

2023-09-06 13:20 UTC, robertatakenaka requested changes
@samuelveigarangel precisa fazer uns ajustes

2023-09-06 13:22 UTC, robertatakenaka commented on journal/fixtures/INDEX_AT.xlsx
@samuelveigarangel este archivo é uma amostra ou é o original? se for o original, remova, insira uma amostra

2023-09-11 12:47 UTC, robertatakenaka commented on journal/choices.py
> +    ("Psicanalise", _("Psicanalise")),
@samuelveigarangel o item Psicanalise foi inserido incorretamente. Devemos remover. O registro que tiver este dado, deve ficar sem nada ou no máximo como "Health Sciences" no lugar.

2023-09-11 12:50 UTC, robertatakenaka commented on journal/models.py
> +    )
@samuelveigarangel coloque o `max_length=32`, pois não é garantia que os valores serão pequenos, que comecem com 1.

2023-09-11 12:52 UTC, robertatakenaka commented on journal/models.py
> +        FieldPanel("indexed_at"),
@samuelveigarangel aqui acho que seria InlinePanel ou Autocomplete para indexed_at, pois o usuário vai selecionar vários

2023-09-11 12:57 UTC, robertatakenaka commented on journal/models.py
> +
Similar ao comentário:
https://github.com/scieloorg/core/pull/332/files#r1321509984

2023-09-11 12:58 UTC, robertatakenaka commented on journal/models.py
> +            raise Exception("Unable to create or update IndexedAt")
similar a https://github.com/scieloorg/core/pull/332/files#r1321509984

2023-09-11 13:01 UTC, samuelveigarangel commented on journal/models.py
> +            raise Exception("Unable to create or update IndexedAt")
Feito em: https://github.com/scieloorg/core/pull/337

2023-09-11 13:01 UTC, samuelveigarangel commented on journal/models.py
> +        raise Exception("IndexedAt.get requires name or acronym paraments")
Feito em: https://github.com/scieloorg/core/pull/337

2023-09-11 13:01 UTC, samuelveigarangel commented on journal/models.py
> +
Feito em: https://github.com/scieloorg/core/pull/337

2023-09-11 13:02 UTC, robertatakenaka commented on journal/scripts/load_indexedat_xlsx.py
> +    workbook = openpyxl.load_workbook(xlsx_file_path)
Trocar
```python
def run():
    xlsx_file_path = 'journal/fixtures/INDEX_AT.xlsx'
```
por 
```python
def run(xlsx_file_path):
```
O arquivo journal/fixtures/INDEX_AT.xlsx não deve ser versionado, exceto ser for uma amostra, um modelo com poucos dados

2023-09-11 13:04 UTC, robertatakenaka requested changes
@samuelveigarangel fazer os ajustes solicitados

2023-09-12 11:10 UTC, robertatakenaka commented on core/choices.py
> +    (12, _("December")),
@samuelveigarangel os valores devem ser "strings" apesar de números pois facilita a montagem de data em formato YYYY-MM-DD, além disso no XML os dados são string.
Ao fazer as validações entre data do registro dos fascículos e a data encontrada no XML é desejável que esteja como string, evitará ter que fazer conversões de tipo

2023-09-12 11:14 UTC, robertatakenaka requested changes
@samuelveigarangel corrigir https://github.com/scieloorg/core/pull/332/files#r1322879827 que não observei nas vezes anteriores

2023-10-24 15:31 UTC, merged