WIP: Refatora modelo de Journals
scieloorg/core pull request #352
Opened 2023-09-22 14:01 UTC by samuelveigarangel

#### O que esse PR faz?
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.

#### Onde a revisão poderia começar?
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.

#### Como este poderia ser testado manualmente?
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.

#### Algum cenário de contexto que queira dar?
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.

### Screenshots
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.

#### Quais são tickets relevantes?
Indique uma issue ao qual o pull request faz relacionamento.

### Referências
Indique as referências utilizadas para a elaboração do pull request.

2023-09-22 18:44 UTC, robertatakenaka commented on core/models.py
> +            license = cls.get(
@samuelveigarangel remover license_p do get, pois não é um campo chave

2023-09-22 18:45 UTC, robertatakenaka commented on core/models.py
> +        license.updated_by = user
@samuelveigarangel preferencialmente a atribuição de updated_by deve ser entre 246 e 247

2023-09-22 18:46 UTC, robertatakenaka commented on core/models.py
> +        return self.url or self.license_p or self.license_type or ""
@samuelveigarangel a melhor ordem é type, url e p

2023-09-22 18:46 UTC, robertatakenaka commented on institution/models.py
> +    copyright_holder = models.TextField(_("Copy Right Holder"), null=True, blank=True)
copyright é junto

2023-09-22 18:48 UTC, robertatakenaka commented on institution/models.py
> +        raise ValueError("Requires inst_name or inst_acronym paramenters")
~paramenters~ parameters

2023-09-22 18:50 UTC, robertatakenaka commented on institution/models.py
> +    def get(
@samuelveigarangel é altamente provável ocorrer MultipleReturnedObjects pois pode haver registros de nome + acron, nome somente, acron somente, com ou sem combinação de localidade

2023-09-22 18:51 UTC, robertatakenaka commented on institution/models.py
> +    copyright_holder = models.TextField(_("Copy Right Holder"), null=True, blank=True)
Copyright holder deveria ser um Modelo que herda de Institution.

2023-09-22 18:52 UTC, robertatakenaka commented on institution/models.py
> +        institution.copyright_holder = copyright_holder or institution.copyright_holder
remover. Copyright holder não é um atributo de instituição. É uma instituição

2023-09-22 19:00 UTC, robertatakenaka commented on journal/models.py
> +    old_title = models.TextField(_("Old Title"), null=True, blank=True)
@samuelveigarangel deve ser `new_title = models.ForeignKey("self", null=True, blank=True)`
`old_title = models.ForeignKey("self", _("Old Title"), null=True, blank=True)`

2023-09-22 19:02 UTC, robertatakenaka commented on journal/models.py
> +    url_of_journal = models.URLField(
poderia ter mantido journal_url e _('Journal URL')

2023-10-03 10:57 UTC, robertatakenaka commented on issue/models.py
> +        raise Exception("TocSections.get requires value and language paramenters")
@samuelveigarangel criar exceções específicas, neste caso: IssueGetError

2023-10-03 10:57 UTC, robertatakenaka commented on core/models.py
> +        raise Exception("License.get requires url, language or url paramenter")
@samuelveigarangel criar exceções específicas, neste caso: LicenseGetError

2023-10-03 10:58 UTC, robertatakenaka commented on core/models.py
> +        if license_p:
@samuelveigarangel license_p é texto, não acho que é uma boa chave. Isso deve ser usado em último caso.

2023-10-03 11:01 UTC, robertatakenaka commented on article/models.py
> +        raise Exception("DocumentTitle requires title and language paramenters")
@samuelveigarangel criar exceções específicas, neste caso: TitleGetError. Mas acho que o problema maior é considerar que title é chave. Artigos diferente podem vir a ter o mesmo valor, além disso há documentos que não possuem título. E a mensagem considera idioma e não há idioma como parâmetro. Olhe a grafia de `paramenters`

2023-10-16 13:00 UTC, robertatakenaka commented on institution/models.py
> +            history.institution = institution
isso não causa erro já que não existe institution neste modelo?

2023-10-16 13:03 UTC, robertatakenaka commented on issue/exceptions.py
> +        super().__init__(f"Error while getting TocSection: Requires value and language parameters")
@samuelveigarangel não precisa disso

2023-10-16 13:04 UTC, robertatakenaka commented on issue/models.py
> +        raise TocSectionGetError()
Troque:
`raise TocSectionGetError()`

por

`raise TocSectionGetError("TocSections.get requires value and language paramenters")`

2023-10-16 13:07 UTC, robertatakenaka commented on journal/models.py
> +    panels_legacy_compatibility_fields = [
faltou colocar no TabbedInterface?

2023-10-16 13:12 UTC, robertatakenaka commented on journal/models.py
> +    update_date = models.DateField(_("Update Date"), blank=True, null=True)
será que precisa? O CommonControlField já possui created e updated

2023-10-16 13:23 UTC, robertatakenaka commented on location/models.py
> +
Melhor adicionar um atributo location aqui

2023-10-16 13:24 UTC, robertatakenaka requested changes
Verificar os comentários e realizar as correções

2023-10-16 20:38 UTC, samuelveigarangel commented on institution/models.py
> +            history.institution = institution
Como ela é uma classe abstrata, ela não representa uma tabela real no banco de dados. Serve apenas de um modelo Base para ser herdado em outros modelos.

2023-10-16 20:45 UTC, samuelveigarangel commented on journal/models.py
> +    update_date = models.DateField(_("Update Date"), blank=True, null=True)
Nao seria para informacoes de update e creation legados do article meta?

2023-10-16 20:53 UTC, samuelveigarangel commented on location/models.py
> +    address = models.ForeignKey(
Neste caso, o sentido de criar este campo, seria armazenar informacoes gerais sobre o endereço, no article-meta, vem informações como estas:

```
Ex 1:
[{'_': 'Alameda Jaú, 684, 7ºandar'}, {'_': '01420-001 São Paulo/SP Brasil'}, {'_': 'Tel/Fax: (55 11) 3873-4211'}]

Ex 2:
[{'_': 'Avenida Dr. Arnaldo, 715, São Paulo, SP, BR, 01246-904, 55 11 3068-0539'}]

Ex 3:
[{'_': 'Quinta Avenida, 1100, bloco 7'}, {'_': 'CEP: 88337-300'}, {'_': 'Balneário Camboriú, SC - Brasil'}, {'_': 'Tel.: (47)3261-1315'}]
```

2023-10-24 15:31 UTC, merged