Refactor: Modifica o modelo Journal (URI para repositório de dados, Títulos em Bases de Dados, Preservação digital, outros)
scieloorg/core pull request #550
Opened 2024-01-08 20:24 UTC by samuelveigarangel

#### O que esse PR faz?
 Modifica o modelo Journal (URI para repositório de dados, Títulos em Bases de Dados, Preservação digital, outros)

#### Onde a revisão poderia começar?
pelo commit https://github.com/scieloorg/core/commit/685f8b932fd5574fad9efc171c048eee45589f6c

#### Como este poderia ser testado manualmente?
```console
python manage.py runscript load_journal_from_am_journal --script-args adm scl
```

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
https://github.com/scieloorg/core/issues/526

### Referências
N/A

2024-01-08 20:29 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +            cleaned_domain_query = url_of_the_main_collection.replace("http://", "").replace("https://", "")
@samuelveigarangel verdade!

2024-01-08 21:26 UTC, robertatakenaka commented on journal/models.py
> +        InlinePanel("focus", label=_("Focus and Scope"), classname="collapsed"),
@samuelveigarangel a ordem não está conforme solicitado
<img width="813" alt="Captura de Tela 2024-01-08 às 18 26 32" src="https://github.com/scieloorg/core/assets/505143/7528f83e-38b8-4c32-84be-96ec30e68b94">

2024-01-08 21:27 UTC, robertatakenaka commented on journal/models.py
> +        unique_together = [( "journal", "indexed_at", "journal")]
@samuelveigarangel journal está duplicado

2024-01-08 21:28 UTC, robertatakenaka commented on journal/models.py
> +            obj.journal = journal
@samuelveigarangel adicionar creator

2024-01-08 21:29 UTC, robertatakenaka commented on journal/models.py
> +        journal,
adicionar `user,`

2024-01-08 21:29 UTC, robertatakenaka commented on journal/models.py
> +        journal,
adicionar user,

2024-01-08 21:29 UTC, robertatakenaka commented on journal/models.py
> +                journal=journal,
adicionar user,

2024-01-08 21:30 UTC, robertatakenaka commented on journal/models.py
> +class DataRepositoryURI(Orderable, CommonControlField):
O modelo pode ser chamar `DataRepository`

2024-01-08 21:35 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +    update_title_in_database(journal=journal, code=secs_code, acronym="medline", title=medline_short_title)
seria medline_code

2024-01-08 21:38 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +    indexed_at = IndexedAt.get(name=None, acronym=acronym)
Esta linha resultará comportamento indesejado. Possíveis correções:

Opção 1:
```python
 indexed_at = IndexedAt.objects.get(acronym=acronym)
```

Opção 2:
```python
# passar o name conforme foi pré-cadastrado
 indexed_at = IndexedAt.get(name=name, acronym=acronym)
```

2024-01-08 21:40 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +    update_title_in_database(journal=journal, code=secs_code, acronym="secs")
@samuelveigarangel prefira passar explicitamente title para **SeCS**

2024-01-08 21:41 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +        title = extract_value(title)
```python
title = title or extract_value(title)
```

2024-01-08 21:42 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +    update_title_in_database(journal=journal, code=secs_code, acronym="medline", title=medline_short_title)
@samuelveigarangel

2024-01-08 21:46 UTC, robertatakenaka requested changes
Correções necessárias

2024-01-09 16:14 UTC, robertatakenaka commented on journal/models.py
> +                identifier=identifier,
@samuelveigarangel se o unique_together tem apenas `journal, index_at`, então só estes devem compor os parâmetros de `get()`

2024-01-09 16:16 UTC, robertatakenaka commented on journal/models.py
> +    def __str__(self):
remove self.journal

2024-01-09 16:34 UTC, samuelveigarangel commented on journal/models.py
> +                identifier=identifier,
@robertatakenaka  Pode ter mais de um secs_code ou medline_code por journal?

2024-01-09 18:57 UTC, merged