Obtención de logos de revistas
scieloorg/core pull request #604
Opened 2024-02-09 17:18 UTC by eduranm

#### O que esse PR faz?
Tarea para obtener logos de las revistas

#### Onde a revisão poderia começar?
Por commit

#### Como este poderia ser testado manualmente?
N/A

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://github.com/scieloorg/core/assets/58487702/aae0b847-c7fa-4290-b776-f24d6f9c5b19)

#### Quais são tickets relevantes?
https://github.com/scieloorg/core/issues/524

### Referências
N/A

2024-02-14 20:13 UTC, samuelveigarangel commented on journal/sources/am_to_core.py
> +    response = requests.get(url_logo)
Utillizar a funcao fetch_data para fazer requisicoes:
```python
from core.utils.utils import fetch_data
```

2024-02-14 20:15 UTC, samuelveigarangel commented on journal/sources/article_meta.py
> +            am_to_core.update_logo(
Colocar estes dados como parametro em 'update_panel_website' e realizar a chamada de 'update_logo' dentro dela.

2024-02-14 20:19 UTC, samuelveigarangel commented on journal/sources/am_to_core.py
> +        url_logo = f"http://{domain}/media/images/{journal_acron}_glogo.gif"
https://

2024-02-20 19:53 UTC, robertatakenaka commented
@eduranm por favor, aplicar las recomendaciones de samuel

2024-02-21 17:40 UTC, eduranm commented on journal/sources/am_to_core.py
> +    response = requests.get(url_logo)
Hice el cambio para utilizar fetch_data
Pero utilicé json=False porque obtenía error en response.json()
Con json=False obtengo response.content y es lo que asigno a logo_data

2024-02-21 17:40 UTC, eduranm commented on journal/sources/article_meta.py
> +            am_to_core.update_logo(
Realicé los cambios como sugeriste

2024-02-21 18:36 UTC, eduranm commented on journal/sources/am_to_core.py
> +        url_logo = f"http://{domain}/media/images/{journal_acron}_glogo.gif"
Ok, ya hice el cambio

2024-02-21 20:03 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +    response = requests.get(url_logo)
@eduranm correcto, pues el resultado es una imagen y no un JSON

2024-02-21 20:43 UTC, robertatakenaka commented on journal/sources/am_to_core.py
> +import requests
@eduranm puede ser removido

2024-02-21 21:04 UTC, robertatakenaka requested changes
Verificar los comentários

2024-02-22 19:22 UTC, eduranm commented on journal/sources/am_to_core.py
> +import requests
Eliminé
import requests

2024-02-23 11:24 UTC, robertatakenaka approved these changes

2024-02-23 11:24 UTC, merged