Implementa o InlinePanel para 'Other Titles' e Atualiza o Procedimento de Atribuição do Logo dos Periódicos
scieloorg/core pull request #641
Opened 2024-02-27 20:44 UTC by samuelveigarangel

#### O que esse PR faz?
Implementa o InlinePanel para 'Other Titles' e Atualiza o Procedimento de Atribuição do Logo dos Periódicos

#### Onde a revisão poderia começar?
Pelo commit https://github.com/scieloorg/core/commit/b0a017008a6d1138d6c869de2ee9b2709073dc06

#### Como este poderia ser testado manualmente?

1. make django_bash

2.
```cli
python manage.py runscript load_journal_logo --script-args {username}
```
3.
```cli
python manage.py runscript  load_journal_from_am_journal --script-args {username}
```

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://github.com/scieloorg/core/assets/82840278/4b73d59e-1f77-481e-98c0-bed3a23ca9e4)

#### Quais são tickets relevantes?
#635
 
### Referências
N/A

2024-02-27 21:22 UTC, robertatakenaka commented on reference/models.py
> +        return cls.objects.get(title=title)
@samuelveigarangel tem que adicionar o journal como parâmetro de get, também criar unique_together (journal, title) em Meta

2024-02-27 21:24 UTC, samuelveigarangel commented on reference/models.py
> +        return cls.objects.get(title=title)
https://github.com/scieloorg/core/pull/641/commits/ee7dcd18b48a064779f40870df72985f8e149e8e

2024-02-27 21:26 UTC, robertatakenaka commented on reference/models.py
> +        return cls.objects.get(title=title)
@samuelveigarangel 
Manter este reference.models.JournalTitle do jeito anterior mas antes copiar isso para dentro de journal.models.
Futuramente refatoramos este reference.models.JournalTitle para uso das referências, se necessário.

2024-02-27 21:27 UTC, samuelveigarangel commented on reference/models.py
> +        return cls.objects.get(title=title)
Acho que uma forma de otimizar e, 
```python
journal.other_titles.get(title=title)
```

2024-02-27 21:28 UTC, robertatakenaka requested changes
Verificar comentários

2024-02-28 00:11 UTC, robertatakenaka commented on journal/tasks.py
> +def load_journal_logo(self, user_id=None, username=None):
@samuelveigarangel colocar nome no plural

2024-02-28 00:13 UTC, robertatakenaka commented on journal/tasks.py
> +        )
acrescentar journal.logo e journal.save()

2024-02-28 00:15 UTC, robertatakenaka commented on journal/sources/am_to_core.py
>  def update_logo(
@samuelveigarangel esta função pode ser removida e onde está sua chamada ser substituída pela chamada da task ou substituir o conteúdo de upload_logo pela chamada da task

2024-02-28 00:19 UTC, robertatakenaka commented on journal/tasks.py
> +@celery_app.task(bind=True)
@samuelveigarangel estas tarefas não são necessárias, podem ser removidas. No entanto, as lógicas podem ser incorporadas na função fetch_and_process... com o uso de parâmetros que indicam que é para forçar a atualização  e pular a coleta etc

2024-02-28 00:20 UTC, robertatakenaka requested changes
@samuelveigarangel verificar os comentários

2024-03-05 14:14 UTC, robertatakenaka commented on reference/models.py
> +    journal = ParentalKey(
@samuelveigarangel Deixe intacto o JournalTitle que está em reference, deixe como estava. E crie um novo modelo JournalTitle para o uso dentro de Journal para realizar as mudanças necessárias.

2024-03-05 17:43 UTC, robertatakenaka commented on reference/models.py
> +    journal = ParentalKey(
@samuelveigarangel estas alterações tem que sumir neste PR

2024-03-05 17:44 UTC, robertatakenaka commented on reference/migrations/0002_journaltitle_journal.py
> +# Generated by Django 4.2.7 on 2024-02-26 01:37
@samuelveigarangel remover esta migração

2024-03-05 17:44 UTC, robertatakenaka commented on reference/migrations/0003_alter_journaltitle_unique_together.py
> +# Generated by Django 4.2.7 on 2024-02-27 19:58
@samuelveigarangel remover esta migração

2024-03-05 18:12 UTC, robertatakenaka commented on reference/models.py
> +from django.db import models, IntegrityError
@samuelveigarangel este arquivo está apresentando alterações

2024-03-05 18:14 UTC, robertatakenaka commented on journal/models.py
> -    )
@samuelveigarangel isso foi removido logo não há como fazer `journal.other_titles`... confere?

2024-03-05 18:14 UTC, robertatakenaka commented on journal/models.py
> +        return journal.other_titles.get(title=title)
@samuelveigarangel não deveria ser `cls.objects.get(journal=journal, title=title)`?

2024-03-05 18:16 UTC, samuelveigarangel commented on journal/models.py
> -    )
Ainda ha como fazer pelo related_name em:
```python
   journal = ParentalKey(
        Journal, on_delete=models.SET_NULL, related_name="other_titles", null=True
    )
```

2024-03-05 18:36 UTC, robertatakenaka commented on reference/models.py
> +from django.db import models, IntegrityError
@samuelveigarangel dá um `git checkout -- ` neste arquivo

2024-03-05 20:17 UTC, robertatakenaka approved these changes

2024-03-05 20:17 UTC, merged