Realiza ajustes na API de Journal e Issue.
scieloorg/core pull request #737
Opened 2024-04-19 17:42 UTC by samuelveigarangel

#### O que esse PR faz?
- Modifica os paramentros da API de Journal e Issue.
- Adiciona mais informacoes relacionado ao Issue na API de Issue.
- Realiza ajustes em search_indexes.

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?
Acessar API de Journal  ou Issue.

1. http://0.0.0.0:8009/api/v1/journal/{issn_print}/
2. http://0.0.0.0:8009/api/v1/issue/{issn_print}

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
#736 

### Referências
N/A

2024-05-06 13:53 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            params["season"] = season
@samuelveigarangel remover o filtro season

2024-05-06 13:55 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            "until_date",
@samuelveigarangel adicionar `from_publication_year` e `until_publication_year` (que é diferente do criação do registro)

2024-05-06 13:55 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            "page",
@samuelveigarangel remover page

2024-05-06 13:56 UTC, robertatakenaka commented on journal/api/v1/views.py
> +        title = self.request.query_params.get("title")
@samuelveigarangel adicionar área temática com filtro

2024-05-06 13:58 UTC, robertatakenaka commented on journal/models.py
> +        _("ISSN Electronic"), max_length=9, null=True, blank=True
Electronic ISSN

2024-05-06 13:58 UTC, robertatakenaka commented on journal/models.py
>      issn_print_is_active = models.BooleanField(verbose_name=_("ISSN Print is active"), default=False)
Print ISSN

2024-05-06 13:59 UTC, robertatakenaka requested changes
Verificar comentários

2024-05-06 15:08 UTC, samuelveigarangel commented on issue/api/v1/views.py
> +            "until_date",
Faz mais sentido remover from_date e until_date e substituir por esses, correto?

2024-05-06 19:25 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            params["year__lte"] = until_date.replace("/", "-")
@samuelveigarangel documentar que o formato é com hífen. O formato com barra deveria ser recusado

2024-05-06 19:28 UTC, robertatakenaka commented on issue/api/v1/views.py
> -        until_date = self.request.query_params.get("until_date")
@samuelveigarangel manter, isso é importante para obter os registros mais recentes.

2024-05-06 19:28 UTC, robertatakenaka commented on issue/api/v1/views.py
> -            params["created__lte"] = until_date.replace("/", "-")
@samuelveigarangel trocar created por updated, isso é importante para obter os registros mais recentes

2024-05-07 13:26 UTC, samuelveigarangel commented on issue/api/v1/views.py
> +            params["year__lte"] = until_date.replace("/", "-")
Acha que nao e melhor manter as duas formas?

2024-05-08 11:15 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            params["year__lte"] = until_date.replace("/", "-")
@samuelveigarangel não, é uma API, na documentação deve ter a forma de uso

2024-05-08 11:18 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            "until_date",
Manter os dois. O filtro de publicação é para o usuário obter os registros de determinados anos de publicação. O update é para identificar os registros que sofreram alterações. Ambos são importantes, tem caso de uso próprios.

2024-05-08 11:26 UTC, robertatakenaka commented on issue/api/v1/views.py
> +            parâmetros que recuperam registros a partir da data de atualização do periódico.
@samuelveigarangel considerar adicionar docstring de documentação seguindo o padrão https://pandas.pydata.org/docs/development/contributing_docstring.html

2024-05-09 12:37 UTC, merged