Disponibiliza o campo doi_prefix na API Journal
scieloorg/core pull request #830
Opened 2024-08-01 06:09 UTC by samuelveigarangel

#### O que esse PR faz?
Disponibiliza o campo doi_prefix na API Journal

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?
Acessa: http://0.0.0.0:8009/api/v1/journal/

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
#829 

### Referências
N/A

2024-08-01 06:12 UTC, samuelveigarangel commented
@robertatakenaka, Eu adiciono um filtro pelo campo doi_prefix para retornar todos os periódicos que possuem um valor para doi_prefix?

2024-08-05 13:19 UTC, robertatakenaka commented on article/api/v1/views.py
> +        return queryset
@samuelveigarangel qual é o propósito?

2024-08-06 18:15 UTC, samuelveigarangel commented on article/api/v1/views.py
> +        return queryset
Filtar os artigos pelo o prefixo do doi. Não há necessidade?

2024-08-06 21:25 UTC, robertatakenaka commented on article/api/v1/views.py
> +        return queryset
@samuelveigarangel ok, mas não acho que há este caso de uso... mas se houver a consulta é diretamente no Article, não seria necessário o filter ser pelo journal, está esquisito. Que tal:

```python

def get_queryset(self):
        doi_prefix = self.request.query_params.get('doi_prefix', None)
        if doi_prefix is not None:
            return models.Article.objects.filter(doi__value__startswith=doi_prefix)
        return models.Article.objects.all()

```

O tamanho 50 para o prefixo está muito grande. O tamanho total indicado para o DOI está como 100.
Consulte: https://www.crossref.org/documentation/member-setup/constructing-your-dois/

2024-08-06 21:25 UTC, robertatakenaka commented on journal/models.py
> +    doi_prefix = models.CharField(max_length=50, blank=True, null=True)
@samuelveigarangel 
O tamanho 50 para o prefixo está muito grande. O tamanho total indicado para o DOI está como 100.
Consulte: https://www.crossref.org/documentation/member-setup/constructing-your-dois/

2024-08-14 11:39 UTC, robertatakenaka commented on journal/migrations/0027_journal_doi_prefix.py
> +            field=models.CharField(blank=True, max_length=100, null=True),
@samuelveigarangel O meu comentário anterior diz que 50 para doi_prefix é muito, então 100, é demais

![image](https://github.com/user-attachments/assets/0c66f399-2518-48a2-9693-09419d4b3207)

2024-08-14 11:46 UTC, robertatakenaka requested changes
@samuelveigarangel Realizar correções

2024-08-15 01:06 UTC, samuelveigarangel commented on journal/migrations/0027_journal_doi_prefix.py
> +            field=models.CharField(blank=True, max_length=100, null=True),
Entendi seu comentário de forma errada e pensei que era para aumentar o tamanho. Pesquisei sobre o limite do tamanho do DOI e a única fonte que encontrei relacionada a isso foi: https://www.doi.org/resources/DOI_article_ELIS3.pdf. Na seção 'syntax', é informado que não há um limite definido para o tamanho do DOI, prefixo ou sufixo.

2024-08-30 19:24 UTC, robertatakenaka approved these changes

2024-10-01 12:52 UTC, merged