Cria Processamento Para Logos dos Periódicos e Adiciona o campo url
scieloorg/core pull request #838
Opened 2024-08-06 18:29 UTC by samuelveigarangel

#### O que esse PR faz?
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.

#### Onde a revisão poderia começar?
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.

#### Como este poderia ser testado manualmente?
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.

#### Algum cenário de contexto que queira dar?
Indique um contexto onde as modificações se fazem necessárias ou passe informações que contextualizam
o revisor a fim de facilitar o entendimento da funcionalidade.

### Screenshots
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que o pull request resolve.

#### Quais são tickets relevantes?
Indique uma issue ao qual o pull request faz relacionamento.

### Referências
Indique as referências utilizadas para a elaboração do pull request.

2024-08-06 20:57 UTC, robertatakenaka commented on journal/models.py
> +    url_logo = models.URLField(
@samuelveigarangel no lugar de criar um novo campo, vc poderia usar o link para a imagem (campo logo, linha 2512)

2024-08-06 21:02 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +    previous_journal_titles = serializers.CharField(source="official.previous_journal_titles")
@samuelveigarangel next_journal_title e previous_journal_titles deveriam ter além dos títulos, também outros atributos, como issns e acrônimos, pois eles serão links no site para outros periódicos. Imagina que o título C tem um título anterior B. No site haverá um link de B para C, então terá que ter todos os mesmos elementos necessário para montar os links.

2024-08-06 21:03 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +    sponsor = serializers.SerializerMethodField()
@samuelveigarangel por que não é similar a Mission?

2024-08-06 21:05 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +    sponsor = serializers.SerializerMethodField()
@samuelveigarangel neste PR não encontrei a parte "Cria Processamento Para Logos "

2024-08-06 21:14 UTC, samuelveigarangel commented on journal/api/v1/serializers.py
> +    sponsor = serializers.SerializerMethodField()
other_titles só há um campo 'title', então achei mais fácil fazer desta forma do que criar uma class serializer para other_ttitles.
Ao acessar os atributos de sponsor, owner, copyright e publisher, estou utilizando métodos que verificam a existência desses atributos nas classes relacionadas, evitando erros de AttibuteError caso algum dos atributos seja None.
Já em Mission não é preciso fazer isto, já que não há classes relacionadas.

2024-08-07 19:15 UTC, samuelveigarangel commented on journal/api/v1/serializers.py
> +    sponsor = serializers.SerializerMethodField()
@robertatakenaka https://github.com/scieloorg/core/pull/838/commits/c56fba0c97c80a47d37e13771024a909c8cf343a

2024-08-12 13:06 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +            if not domain.startswith('https'):
@samuelveigarangel alguns sites clássicos não tem https, só http, vai funcionar a coleta?

2024-08-12 13:08 UTC, robertatakenaka commented on institution/models.py
> +            return self.institution.institution.institution_identification.name
@samuelveigarangel tem que retornar str sempre. Também teria que testar a existência de self.institution.institution.institution_identification

```python
try:
    return self.institution.institution.institution_identification.name
except AttributeError:
    return ''
```

2024-08-12 13:12 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +                "issn_electronic": obj.official.new_title.issn_electronic,
@samuelveigarangel o next_journal_title pode estar preenchido, mas o new_title não.

2024-08-12 13:14 UTC, robertatakenaka requested changes
@samuelveigarangel verificar os comentários

2024-08-14 11:27 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +            journal_new_title = obj.filter(title__icontains=obj.official.next_journal_title)
@samuelveigarangel filter retornará um queryset, então ocorrerá erro nas linhas 169 e 170. Além disso, tem que considerar que pode não existir.

2024-08-14 11:28 UTC, robertatakenaka commented on journal/api/v1/serializers.py
> +            old_journal = obj.official.old_title.get(
@samuelveigarangel este trecho está estranho

2024-08-14 11:30 UTC, robertatakenaka commented on institution/models.py
> +            return getattr(self.institution.institution.institution_identification, 'name', '')
@samuelveigarangel 
Use: 
```python
try:
     return self.institution.institution.institution_identification.name
except AttributeError:
     return ''

```

2024-08-19 13:10 UTC, robertatakenaka approved these changes
@samuelveigarangel parece ok

2024-09-03 17:08 UTC, merged