Fix: Corrige forma dos artigos serem selecionados por data.
scieloorg/core pull request #876
Opened 2024-10-14 12:54 UTC by samuelveigarangel

#### O que esse PR faz?
Corrige forma dos artigos serem selecionados por data.

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?
Executar carga de artigos

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
N/A

#### Quais são tickets relevantes?
#869 

### Referências
Indique as referências utilizadas para a elaboração do pull request.

2024-12-02 13:48 UTC, robertatakenaka commented on article/tasks.py
> +            from_date = last_valid_article.updated
@samuelveigarangel pensando melhor: a data do último artigo criado ou atualizado não vai garantir a seleção adequada dos registros de PidProvider. Como o procedimento de carga de artigos não está sincronizado com o recebimento de XML, a seleção dos registros de PidProvider pode não ser completa. 
Para resolver este problema, faça o seguinte:

No lugar de

```python
        last_valid_article = Article.objects.all().order_by("-updated").first()
        if last_valid_article:
            from_date = last_valid_article.updated 

```
use:

```python
        last_created_article = Article.objects.all().order_by("-created").first()
        if last_created_article:
            pid_v3 = last_created_article.pid_v3
            from_date = PidProviderXML.objects.filter(v3=pid_v3).order_by("created").first().created

```

2024-12-02 13:49 UTC, robertatakenaka requested changes
@samuelveigarangel fazer a correção

2024-12-13 14:13 UTC, robertatakenaka commented on article/tasks.py
> +        return PidProviderXML.objects.filter(~Q(v3__in=articles) | Q(updated__gte=F("created") + timedelta(days=1))).iterator()
@samuelveigarangel cuidado que tem artigos que ainda não está publicados nos respectivos sites das coleções, adiciona o filtro que só pega os artigos publicados (public_items)

2024-12-13 17:03 UTC, robertatakenaka commented on article/tasks.py
> +        return PidProviderXML.objects.filter(Q(available_since__isnull=True) | Q(available_since__lte=now)).filter(~Q(v3__in=articles) | Q(updated__gte=F("created") + timedelta(days=5))).iterator()
@samuelveigarangel achei muito aleatório o valor 5. Melhor colocar como parâmetro e sugiro que o 1 seja o valor default.

2024-12-13 17:05 UTC, samuelveigarangel commented on article/tasks.py
> +        return PidProviderXML.objects.filter(Q(available_since__isnull=True) | Q(available_since__lte=now)).filter(~Q(v3__in=articles) | Q(updated__gte=F("created") + timedelta(days=5))).iterator()
Foi um error de digitação. Vou voltar.

2024-12-13 17:05 UTC, samuelveigarangel commented on article/tasks.py
> +        return PidProviderXML.objects.filter(Q(available_since__isnull=True) | Q(available_since__lte=now)).filter(~Q(v3__in=articles) | Q(updated__gte=F("created") + timedelta(days=5))).iterator()
Bem pontuado

2024-12-16 11:44 UTC, robertatakenaka approved these changes

2024-12-16 11:44 UTC, merged