Custumiza a representação de Journal nos Autocompletelabel
scieloorg/core pull request #897
Opened 2024-12-06 15:08 UTC by samuelveigarangel

#### O que esse PR faz?
Custumiza a representação de Journal nos Autocompletelabel

#### Onde a revisão poderia começar?
pelos commits

#### Como este poderia ser testado manualmente?

1. Na área administrativa, ir em Issue.
2. Criar um novo Issue
3. Verificar a representação no campo Journal

#### Algum cenário de contexto que queira dar?
N/A

### Screenshots
![image](https://github.com/user-attachments/assets/2da176e0-7a0e-4131-b1ce-8aa682b6290f)

#### Quais são tickets relevantes?
#896 

### Referências
N/A

2024-12-09 14:00 UTC, robertatakenaka commented on journal/models.py
> +        active_collection = SciELOJournal.objects.filter(journal=self, collection__is_active=True).first()
@samuelveigarangel coloque todas as coleções não somente a primeira. Por exemplo: Revista de Saúde Pública é a mesma na Coleção SciELO Saúde Pública e SciELO Brasil.

No entanto, Educación Superior (bol) e Educación Superior (dom) são mesmo título, mas não é a mesma revista.

2024-12-09 14:02 UTC, robertatakenaka requested changes
@samuelveigarangel corrigir

2024-12-09 17:14 UTC, samuelveigarangel commented
![image](https://github.com/user-attachments/assets/f7525418-af4f-4c52-8c99-706663e14821)

2024-12-10 19:46 UTC, robertatakenaka approved these changes

2024-12-10 19:46 UTC, merged